# Generated by Django 4.0 on 2022-06-20 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_owner', to='auctions.user'),
        ),
        migrations.AddField(
            model_name='auction',
            name='pricebidder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_pricebidder', to='auctions.user'),
        ),
        migrations.AddField(
            model_name='auction',
            name='watchuser',
            field=models.ManyToManyField(blank=True, null=True, related_name='rel_watchuser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='commentuser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_commentuser', to='auctions.user'),
        ),
    ]
