# Generated by Django 4.0 on 2022-06-20 19:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_owner_auction_pricebidder_auction_watchuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='watchuser',
            field=models.ManyToManyField(blank=True, related_name='rel_watchuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
